# Generated by Django 3.2.8 on 2023-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='图片名字')),
                ('eye_status', models.CharField(default='', max_length=100, verbose_name='眼睛状态')),
                ('yawn', models.BooleanField(default=False, verbose_name='是否打哈欠')),
                ('status', models.BooleanField(default=False, verbose_name='是否疲劳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'pic',
            },
        ),
    ]
