# Generated by Django 3.2.8 on 2024-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='车品牌')),
                ('path', models.CharField(default='123', max_length=255, verbose_name='车标路径')),
                ('county', models.CharField(default='', max_length=50, verbose_name='国家')),
                ('desc', models.TextField(verbose_name='介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarKnowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50, verbose_name='主题')),
                ('desc', models.TextField(verbose_name='介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'car_knowledge',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='图片名')),
                ('path', models.CharField(default='123', max_length=255, verbose_name='图片路径')),
                ('xh', models.CharField(default='', max_length=50, verbose_name='型号')),
                ('color', models.CharField(default='', max_length=50, verbose_name='颜色')),
                ('type', models.CharField(default='小轿车', max_length=50, verbose_name='车类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'pic',
            },
        ),
    ]
